// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mineruToken": string;
      "mineruModelVersion": string;
      "mineruLanguage": string;
      "mineruEnableOCR": boolean;
      "mineruEnableTable": boolean;
      "mineruEnableFormula": boolean;
    };
  }
}
